spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/documents}
    username: ${SPRING_DATASOURCE_USERNAME:documents}
    password: ${SPRING_DATASOURCE_PASSWORD:documents}
